jessie-all:
  stage: build
  image: grase/build-images:jessie
  script:
    - dch -v $(git describe |tr '-' '.')~$(lsb_release -cs) -b ""
    - dpkg-buildpackage
    - mkdir artifacts
    - mv -v ../grase-conf-freeradius_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

trusty-all:
  stage: build
  image: grase/build-images:trusty
  script:
    - dch -v $(git describe |tr '-' '.')~$(lsb_release -cs) -b ""
    - dpkg-buildpackage
    - mkdir artifacts
    - mv -v ../grase-conf-freeradius_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

xenial-all:
  stage: build
  image: grase/build-images:xenial
  script:
    - dch -v $(git describe |tr '-' '.')~$(lsb_release -cs) -b ""
    - dpkg-buildpackage
    - mkdir artifacts
    - mv -v ../grase-conf-freeradius_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week
