.build_template: &build_definition
  stage: build
  script:
    - dch -v $(git describe |tr '-' '.')~$(lsb_release -cs) -b ""
    - dpkg-buildpackage
    - mkdir artifacts
    - mv -v ../grase-conf-freeradius_* artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week


jessie-all:
  <<: *build_definition
  image: grase/build-images:jessie

trusty-all:
  <<: *build_definition
  image: grase/build-images:trusty

xenial-all:
  <<: *build_definition
  image: grase/build-images:xenial

bionic-php56-all:
  <<: *build_definition
  image: grase/build-images:bionic-php56
