#!/bin/sh -e
# config maintainer script for grase-conf-freeradius

# source debconf stuff
. /usr/share/debconf/confmodule
# we support mysql and pgsql
dbc_first_version=1.0
dbc_dbtypes="mysql"
dbc_dbname="radius"
dbc_dbuser="radius"
dbc_dbpassword=""
# source dbconfig-common stuff
. /usr/share/dbconfig-common/dpkg/config 
dbc_go grase-conf-freeradius $@


