#!/bin/sh -e

action="$1"
oldversion="$2"

umask 022

# source debconf stuff
. /usr/share/debconf/confmodule
# source dbconfig-common stuff
. /usr/share/dbconfig-common/dpkg/postinst.mysql

mkdir -p /etc/grase/

dbc_first_version=3.0
dbc_generate_include="template:/etc/grase/radius.conf"
dbc_generate_include_perms="660"
dbc_generate_include_owner="freerad:www-data"
dbc_generate_include_args="-o template_infile=/usr/share/grase/templates/radius.conf -U"

dbc_go grase-conf-freeradius $@

## Generate second config file
dbconfig-generate-include -a -f template -O root:freerad -m 640 -o template_infile=/usr/share/grase/templates/sql.conf.grase /etc/dbconfig-common/grase-conf-freeradius.conf /etc/freeradius/3.0/mods-available/grasesql
ln -s /etc/freeradius/3.0/mods-available/grasesql /etc/freeradius/3.0/mods-enabled/grasesql
ln -s /etc/freeradius/3.0/mods-available/graseperl /etc/freeradius/3.0/mods-enabled/graseperl

# Disable default and enable ours
rm -f /etc/freeradius/3.0/sites-enabled/default
ln -s /etc/freeradius/3.0/sites-available/default.grase /etc/freeradius/3.0/sites-enabled/grase

if [ "$action" != configure ]
  then
  exit 0
fi

sed -i 's/testing123/hotspotradius/m' /etc/freeradius/3.0/clients.conf

# On the off chance the radius.conf file is wrong, we need to make sure its right
chown freerad:www-data /etc/grase/radius.conf
chown root:freerad /etc/freeradius/3.0/mods-available/grasesql
chmod 640 /etc/freeradius/3.0/mods-available/grasesql


# Fix for Debian/Ubuntu bug to do with Perl
preloader=`grep "export LD_PRELOAD" /etc/default/freeradius || true`
    if [ "$preloader" = "" ]
    then
         #libperl=$(find /usr/lib/ -name "libperl.so*"|awk '(NR == 1 || length < length(shortest)) { shortest = $0 } END { print shortest }')
         touch /etc/default/freeradius
         echo 'export LD_PRELOAD=$(find /usr/lib/ -name "libperl.so*"|sort -n |tail -n 1)' >> /etc/default/freeradius
         #echo "export LD_PRELOAD=$libperl" >> /etc/default/freeradius
    fi

#DEBHELPER#

if which invoke-rc.d >/dev/null 2>&1; then
       invoke-rc.d freeradius restart 3>&- || true
else
       /etc/init.d/freeradius restart 3>&- || true
fi



exit 0
